version: '3.8'

services:
  # Apache and PHP service
  web:
    image: php:8-apache
    container_name: zorbasite
    ports:
      - "8181:80"
    volumes:
      - ../website:/var/www/html
      - ./apache2.conf:/etc/apache2/apache2.conf

